# Generated by Django 4.2.5 on 2024-04-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lamplight",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=10)),
                ("content", models.TextField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
