# Generated by Django 4.2.5 on 2024-04-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lamplight", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lamplight",
            name="content",
            field=models.TextField(max_length=300),
        ),
    ]
