# Generated by Django 4.2.5 on 2023-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lantern", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fortune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=36, unique=True)),
                ("fortune", models.TextField()),
            ],
        ),
    ]
