# Generated by Django 4.2.5 on 2023-09-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lantern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='key',
            field=models.CharField(default='R2VPgXWRRO', max_length=10),
        ),
    ]
