# Generated by Django 4.2.5 on 2024-04-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lantern", "0002_alter_lantern_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lantern",
            name="lanternColor",
            field=models.CharField(
                choices=[
                    ("pink", "pink"),
                    ("green", "green"),
                    ("pruple", "purple"),
                    ("blue", "blue"),
                    ("yellow", "yellow"),
                ],
                default="pink",
                max_length=10,
            ),
        ),
    ]
