# Generated by Django 4.2.5 on 2023-09-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lantern", "0002_fortune"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_category",
                    models.CharField(
                        choices=[
                            ("abuse", "욕설 및 비하"),
                            ("fraud", "개인정보 유출 및 사칭, 사기"),
                            ("explicit", "음란물 또는 불건전한 대화"),
                            ("promotion", "영리목적이나 홍보성 게시글"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "lantern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lantern.lantern",
                    ),
                ),
            ],
        ),
    ]
