# Generated by Django 4.2.5 on 2023-09-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lantern', '0002_alter_report_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='key',
            field=models.CharField(default='iLEYYa7P9m', max_length=10),
        ),
    ]
