# Generated by Django 4.2.5 on 2023-09-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lantern", "0003_alter_report_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="key",
            field=models.CharField(default="dag1Uv9yiA", max_length=10),
        ),
    ]
