# Generated by Django 4.2.5 on 2023-09-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lantern", "0003_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("abuse", "욕설 및 비하"),
                            ("fraud", "개인정보 유출 및 사칭, 사기"),
                            ("explicit", "음란물 또는 불건전한 대화"),
                            ("promotion", "영리목적이나 홍보성 게시글"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="report",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="report",
            name="report_category",
        ),
        migrations.AddField(
            model_name="report",
            name="key",
            field=models.CharField(default="DfVbI3Q7bu", max_length=10),
        ),
        migrations.AddField(
            model_name="report",
            name="categories",
            field=models.ManyToManyField(to="lantern.reportcategory"),
        ),
    ]
