# Generated by Django 4.2.5 on 2023-09-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lantern", "0004_alter_report_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="key",
            field=models.CharField(default="fzDy7cQSzz", max_length=10),
        ),
    ]
