# Generated by Django 4.2.5 on 2023-09-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lantern", "0004_reportcategory_rename_timestamp_report_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="key",
            field=models.CharField(default="M3GtOazQdm", max_length=10),
        ),
    ]
