# Generated by Django 4.2.5 on 2023-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lantern", "0005_alter_lantern_light_bool_alter_report_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lantern",
            name="nickname",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="lantern",
            name="password",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="report",
            name="key",
            field=models.CharField(default="gxijDsptrt", max_length=10),
        ),
    ]
