# Generated by Django 4.2.5 on 2023-09-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lantern", "0005_alter_report_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="key",
            field=models.CharField(default="k6DyPHbEtC", max_length=10),
        ),
    ]
