# Generated by Django 4.2.5 on 2023-09-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lantern", "0006_alter_lantern_nickname_alter_lantern_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="key",
        ),
    ]
