# Generated by Django 4.2.5 on 2023-09-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lantern", "0006_alter_report_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="lantern",
            name="light_bool",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="report",
            name="key",
            field=models.CharField(default="Vqtgl2E0LT", max_length=10),
        ),
    ]
