# Generated by Django 5.0.4 on 2024-04-19 00:48

import lantern.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lantern', '0007_alter_lantern_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=lantern.models.MultiSelectField(choices=[('abuse', '욕설 및 비하'), ('fraud', '개인정보 유출 및 사칭, 사기'), ('explicit', '음란물 또는 불건전한 대화'), ('promotion', '영리목적이나 홍보성 게시글')], max_length=50),
        ),
    ]
