# Generated by Django 4.2.5 on 2023-09-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lantern", "0007_remove_report_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="user_id",
            field=models.CharField(max_length=36, null=True),
        ),
    ]
