# Generated by Django 5.0.4 on 2024-04-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lantern', '0009_alter_lanternreaction_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortune',
            name='user_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
