# Generated by Django 4.2.5 on 2023-09-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lantern', '0009_lantern_is_liked_lantern_is_reported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='key',
            field=models.CharField(default='pmMWQ6SyHC', max_length=10),
        ),
    ]
